<template>
  <main class="mx-auto w-full max-w-[1600px] space-y-6 px-5 py-6 lg:px-8">
    <section class="rounded-2xl border border-gray-200 bg-white p-6 shadow-sm dark:border-slate-700 dark:bg-[#172536]">
      <div class="flex flex-wrap items-center justify-between gap-4">
        <div>
          <p class="text-sm text-gray-500 dark:text-[#d6e2ff]">{{ t('knowledgeSpaces.overview.eyebrow') }}</p>
          <h1 class="mt-1 text-2xl font-semibold text-gray-900 dark:text-[#fdfcff]">{{ t('knowledgeSpaces.overview.title') }}</h1>
          <p class="mt-2 text-sm text-gray-600 dark:text-[#d6e2ff]">{{ t('knowledgeSpaces.overview.description') }}</p>
        </div>
        <div class="flex gap-2"><UButton color="neutral" variant="outline" icon="i-heroicons-arrow-path" :loading="loading" @click="load">{{ t('common.refresh') }}</UButton><UButton icon="i-heroicons-plus-circle" :to="createPath">{{ t('knowledgeSpaces.ui.createSpace') }}</UButton></div>
      </div>
    </section>
    <section class="rounded-2xl border border-slate-200 bg-white dark:border-slate-700 dark:bg-[#0f192a]">
      <header class="border-b border-slate-200 p-5 dark:border-slate-700"><h2 class="font-semibold text-gray-900 dark:text-[#fdfcff]">{{ t('knowledgeSpaces.overview.listTitle') }}</h2><p class="mt-1 text-sm text-gray-600 dark:text-[#d6e2ff]">{{ t('knowledgeSpaces.overview.listDescription') }}</p></header>
      <div v-if="loading" class="p-12 text-center text-sm text-gray-600 dark:text-[#d6e2ff]">{{ t('common.loading') }}</div>
      <div v-else-if="!spaces.length" class="p-12 text-center"><UIcon name="i-heroicons-circle-stack" class="mx-auto size-9 text-gray-400 dark:text-slate-300" /><p class="mt-3 font-medium text-gray-900 dark:text-[#fdfcff]">{{ t('knowledgeSpaces.ui.noSpaces') }}</p><p class="mt-1 text-sm text-gray-600 dark:text-[#d6e2ff]">{{ t('knowledgeSpaces.overview.emptyDescription') }}</p><UButton class="mt-5" icon="i-heroicons-plus-circle" :to="createPath">{{ t('knowledgeSpaces.ui.createSpace') }}</UButton></div>
      <div v-else class="overflow-x-auto"><table class="min-w-full text-left text-sm"><thead class="border-b border-slate-200 text-gray-600 dark:border-slate-700 dark:text-[#d6e2ff]"><tr><th class="px-5 py-3 font-medium">{{ t('knowledgeSpaces.ui.spaceName') }}</th><th class="px-5 py-3 font-medium">{{ t('knowledgeSpaces.ui.department') }}</th><th class="px-5 py-3 font-medium">{{ t('knowledgeSpaces.ui.documentStatus') }}</th><th class="px-5 py-3 font-medium">{{ t('knowledgeSpaces.ui.lastUpdated') }}</th><th class="px-5 py-3 font-medium">{{ t('knowledgeSpaces.ui.actions') }}</th></tr></thead><tbody class="divide-y divide-slate-100 dark:divide-slate-800"><tr v-for="space in spaces" :key="space.uuid"><td class="px-5 py-4 font-medium text-gray-900 dark:text-[#fdfcff]">{{ space.name }}</td><td class="px-5 py-4 text-gray-600 dark:text-[#d6e2ff]">{{ departmentName(space.department_code) }}</td><td class="px-5 py-4"><UBadge :color="spaceStatusColor(space.status)" variant="soft">{{ spaceStatusLabel(space.status) }}</UBadge></td><td class="px-5 py-4 text-gray-600 dark:text-[#d6e2ff]">{{ formatDate(space.updated_at) }}</td><td class="px-5 py-4"><div class="flex min-w-max flex-wrap gap-2"><UButton size="xs" icon="i-heroicons-arrow-up-tray" :to="detailPath(space.uuid, 'documents')">{{ t('knowledgeSpaces.ui.ingest') }}</UButton><UButton size="xs" color="neutral" variant="soft" icon="i-heroicons-link" :to="detailPath(space.uuid, 'sources')">{{ t('knowledgeSpaces.ui.connectDataSource') }}</UButton><UButton size="xs" color="neutral" variant="soft" icon="i-heroicons-list-bullet" :to="detailPath(space.uuid, 'jobs')">{{ t('knowledgeSpaces.ui.ingestionRecords') }}</UButton><UButton size="xs" color="neutral" variant="soft" icon="i-heroicons-adjustments-horizontal" :to="detailPath(space.uuid, 'strategy')">{{ t('knowledgeSpaces.ui.strategy') }}</UButton><UButton size="xs" color="neutral" variant="soft" icon="i-heroicons-magnifying-glass" :to="knowledgeLabPath(space.uuid)">{{ t('knowledgeSpaces.ui.playground') }}</UButton><UButton size="xs" color="error" variant="soft" icon="i-heroicons-trash" :loading="deleting === space.uuid" @click="askDelete(space)">{{ t('common.delete') }}</UButton></div></td></tr></tbody></table></div>
    </section>
    <UModal v-model:open="deleteOpen"><template #content><div class="p-6"><h2 class="text-lg font-semibold text-gray-900 dark:text-[#fdfcff]">{{ t('knowledgeSpaces.ui.deleteSpace') }}</h2><p class="mt-3 text-sm text-gray-600 dark:text-[#d6e2ff]">{{ t('knowledgeSpaces.ui.deleteConfirm') }}</p><div class="mt-6 flex justify-end gap-3"><UButton color="neutral" variant="ghost" @click="deleteOpen = false">{{ t('common.cancel') }}</UButton><UButton color="error" :loading="Boolean(deleting)" @click="deleteSpace">{{ t('common.delete') }}</UButton></div></div></template></UModal>
  </main>
</template>

<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useLocalKnowledgeApi, type LocalKnowledgeSpace } from '~/composables/api/useLocalKnowledge'
import { useDepartmentService, type Department } from '~/composables/api/services/departmentService'
const { t } = useI18n(); const toast = useToast(); const api = useLocalKnowledgeApi(); const departmentsApi = useDepartmentService(); const runtimeConfig = useRuntimeConfig()
const spaces = ref<LocalKnowledgeSpace[]>([]); const departments = ref<Department[]>([]); const loading = ref(false); const deleteOpen = ref(false); const deleteTarget = ref<LocalKnowledgeSpace | null>(null); const deleting = ref('')
const adminBase = computed(() => String(runtimeConfig.public?.pluginAdminBase || '/_p/com.powerx.plugins.base/admin/').replace(/\/+$/, '')); const createPath = computed(() => `${adminBase.value}/knowledge/create`)
function detailPath(uuid: string, section?: string) { if (section === 'documents') return `${adminBase.value}/knowledge/${uuid}/ingestion`; if (section === 'jobs') return `${adminBase.value}/knowledge/${uuid}/records`; if (section === 'strategy') return `${adminBase.value}/knowledge/${uuid}/strategy`; if (section === 'sources') return `${adminBase.value}/knowledge/${uuid}/sources`; return `${adminBase.value}/knowledge/${uuid}` }; function knowledgeLabPath(uuid: string) { return `${adminBase.value}/powerx/knowledge-lab?space_uuid=${encodeURIComponent(uuid)}` }
function flatten(nodes: Department[], out: Department[] = []) { for (const item of nodes) { out.push(item); if (item.children?.length) flatten(item.children, out) }; return out }; const allDepartments = computed(() => flatten(departments.value)); function departmentName(code: string) { return allDepartments.value.find(item => item.code === code)?.name || code }; function formatDate(value: string) { return value ? new Intl.DateTimeFormat().format(new Date(value)) : '-' }
function spaceStatusLabel(status: string) { return t(`knowledgeSpaces.status.${status || 'available'}`) }; function spaceStatusColor(status: string) { return status === 'available' || status === 'active' ? 'success' : status === 'failed' ? 'error' : 'warning' }; function askDelete(space: LocalKnowledgeSpace) { deleteTarget.value = space; deleteOpen.value = true }
async function deleteSpace() { if (!deleteTarget.value) return; deleting.value = deleteTarget.value.uuid; try { await api.deleteSpace(deleteTarget.value.uuid); deleteOpen.value = false; deleteTarget.value = null; await load(); toast.add({ title: t('common.success'), description: t('knowledgeSpaces.ui.spaceDeleted'), color: 'success' }) } catch { toast.add({ title: t('common.error'), description: t('knowledgeSpaces.ui.spaceDeleteFailed'), color: 'error' }) } finally { deleting.value = '' } }
async function load() { loading.value = true; try { const [spaceOut, tree] = await Promise.all([api.spaces(), departmentsApi.getDepartmentTree()]); spaces.value = spaceOut.items || []; departments.value = tree } catch { toast.add({ title: t('common.error'), description: t('knowledgeSpaces.ui.loadFailed'), color: 'error' }) } finally { loading.value = false } }
onMounted(load)
</script>
