<template>
  <KnowledgeSpaceOverviewPanel :spaces="overviewRows" :loading="loading">
    <template #header-actions><UButton color="neutral" variant="outline" icon="i-heroicons-arrow-path" :loading="loading" @click="load">{{ t('common.refresh') }}</UButton><UButton icon="i-heroicons-plus-circle" :to="createPath">{{ t('knowledgeSpaces.ui.createSpace') }}</UButton></template>
    <template #empty-actions><UButton class="mt-5" icon="i-heroicons-plus-circle" :to="createPath">{{ t('knowledgeSpaces.ui.createSpace') }}</UButton></template>
    <template #row-actions="{ space }"><UButton size="xs" icon="i-heroicons-arrow-up-tray" :to="detailPath(space.id, 'documents')">{{ t('knowledgeSpaces.ui.ingest') }}</UButton><UButton size="xs" color="neutral" variant="soft" icon="i-heroicons-link" :to="detailPath(space.id, 'sources')">{{ t('knowledgeSpaces.ui.connectDataSource') }}</UButton><UButton size="xs" color="neutral" variant="soft" icon="i-heroicons-list-bullet" :to="detailPath(space.id, 'jobs')">{{ t('knowledgeSpaces.ui.ingestionRecords') }}</UButton><UButton size="xs" color="neutral" variant="soft" icon="i-heroicons-adjustments-horizontal" :to="detailPath(space.id, 'strategy')">{{ t('knowledgeSpaces.ui.strategy') }}</UButton><UButton size="xs" color="neutral" variant="soft" icon="i-heroicons-magnifying-glass" :to="knowledgeLabPath(space.id)">{{ t('knowledgeSpaces.ui.playground') }}</UButton><UButton size="xs" color="error" variant="soft" icon="i-heroicons-trash" :loading="deleting === space.id" @click="askDeleteById(space.id)">{{ t('common.delete') }}</UButton></template>
  </KnowledgeSpaceOverviewPanel>
    <UModal v-model:open="deleteOpen"><template #content><div class="p-6"><h2 class="text-lg font-semibold text-gray-900 dark:text-[#fdfcff]">{{ t('knowledgeSpaces.ui.deleteSpace') }}</h2><p class="mt-3 text-sm text-gray-600 dark:text-[#d6e2ff]">{{ t('knowledgeSpaces.ui.deleteConfirm') }}</p><div class="mt-6 flex justify-end gap-3"><UButton color="neutral" variant="ghost" @click="deleteOpen = false">{{ t('common.cancel') }}</UButton><UButton color="error" :loading="Boolean(deleting)" @click="deleteSpace">{{ t('common.delete') }}</UButton></div></div></template></UModal>
</template>
<script setup lang="ts">
import KnowledgeSpaceOverviewPanel, { type KnowledgeOverviewRow } from './KnowledgeSpaceOverviewPanel.vue'
import { computed, onMounted, ref } from 'vue'
import { useLocalKnowledgeApi, type LocalKnowledgeSpace } from '~/composables/api/useLocalKnowledge'
import { useDepartmentService, type Department } from '~/composables/api/services/departmentService'
const { t } = useI18n(); const toast = useToast(); const api = useLocalKnowledgeApi(); const departmentsApi = useDepartmentService(); const runtimeConfig = useRuntimeConfig()
const spaces = ref<LocalKnowledgeSpace[]>([]); const departments = ref<Department[]>([]); const loading = ref(false); const deleteOpen = ref(false); const deleteTarget = ref<LocalKnowledgeSpace | null>(null); const deleting = ref('')
const adminBase = computed(() => String(runtimeConfig.public?.pluginAdminBase || '/_p/com.powerx.plugins.base/admin/').replace(/\/+$/, '')); const createPath = computed(() => `${adminBase.value}/knowledge/create`)
function detailPath(uuid: string, section?: string) { if (section === 'documents') return `${adminBase.value}/knowledge/${uuid}/ingestion`; if (section === 'jobs') return `${adminBase.value}/knowledge/${uuid}/records`; if (section === 'strategy') return `${adminBase.value}/knowledge/${uuid}/strategy`; if (section === 'sources') return `${adminBase.value}/knowledge/${uuid}/sources`; return `${adminBase.value}/knowledge/${uuid}` }; function knowledgeLabPath(uuid: string) { return `${adminBase.value}/knowledge/${uuid}/playground` }
function flatten(nodes: Department[], out: Department[] = []) { for (const item of nodes) { out.push(item); if (item.children?.length) flatten(item.children, out) }; return out }; const allDepartments = computed(() => flatten(departments.value)); function departmentName(code: string) { return allDepartments.value.find(item => item.code === code)?.name || code }; function formatDate(value: string) { return value ? new Intl.DateTimeFormat().format(new Date(value)) : '-' }
function spaceStatusLabel(status: string) { return t(`knowledgeSpaces.status.${status || 'available'}`) }; function spaceStatusColor(status: string) { return status === 'available' || status === 'active' ? 'success' : status === 'failed' ? 'error' : 'warning' }; function askDelete(space: LocalKnowledgeSpace) { deleteTarget.value = space; deleteOpen.value = true }
async function deleteSpace() { if (!deleteTarget.value) return; deleting.value = deleteTarget.value.uuid; try { await api.deleteSpace(deleteTarget.value.uuid); deleteOpen.value = false; deleteTarget.value = null; await load(); toast.add({ title: t('knowledgeSpaces.ui.spaceDeleted'), description: t('knowledgeSpaces.ui.spaceDeleted'), color: 'success' }) } catch { toast.add({ title: t('common.error'), description: t('knowledgeSpaces.ui.spaceDeleteFailed'), color: 'error' }) } finally { deleting.value = '' } }
async function load() { loading.value = true; try { const [spaceOut, tree] = await Promise.all([api.spaces(), departmentsApi.getDepartmentTree()]); spaces.value = spaceOut.items || []; departments.value = tree } catch { toast.add({ title: t('common.error'), description: t('knowledgeSpaces.ui.loadFailed'), color: 'error' }) } finally { loading.value = false } }
const overviewRows = computed<KnowledgeOverviewRow[]>(() => spaces.value.map(space => ({ id: space.uuid, name: space.name, department: departmentName(space.department_code), statusLabel: spaceStatusLabel(space.status), statusColor: spaceStatusColor(space.status), updatedAt: formatDate(space.updated_at) })))
function askDeleteById(id: string) { const space = spaces.value.find(item => item.uuid === id); if (space) askDelete(space) }
onMounted(load)
</script>
