<template>
  <main class="mx-auto w-full max-w-[1600px] space-y-6 px-5 py-6 lg:px-8">
    <section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-700 dark:bg-[#172536]"><div class="flex flex-wrap items-start justify-between gap-4"><div><p class="text-sm text-gray-500 dark:text-[#d6e2ff]">{{ t('knowledgeSpaces.overview.eyebrow') }}</p><h1 class="mt-1 text-2xl font-semibold text-gray-900 dark:text-[#fdfcff]">{{ space?.name || t('common.loading') }}</h1><p class="mt-2 text-sm text-gray-600 dark:text-[#d6e2ff]">{{ space ? departmentName(space.department_code) : '' }}</p></div><UButton color="neutral" variant="outline" :to="overviewPath">{{ t('knowledgeSpaces.detail.backToOverview') }}</UButton></div></section>
    <section v-if="loading" class="rounded-2xl border border-slate-200 bg-white p-12 text-center text-sm text-gray-600 dark:border-slate-700 dark:bg-[#0f192a] dark:text-[#d6e2ff]">{{ t('common.loading') }}</section>
    <template v-else-if="space">
      <section class="rounded-2xl border border-slate-200 bg-white dark:border-slate-700 dark:bg-[#0f192a]"><header class="flex flex-wrap items-center justify-between gap-3 border-b border-slate-200 p-5 dark:border-slate-700"><div><h2 class="font-semibold text-gray-900 dark:text-[#fdfcff]">{{ t('knowledgeSpaces.ui.vectorIndexTitle') }}</h2><p class="mt-1 text-sm text-gray-600 dark:text-[#d6e2ff]">{{ t('knowledgeSpaces.ui.vectorIndexDescription') }}</p></div><UButton color="neutral" variant="outline" icon="i-heroicons-cpu-chip" :loading="vectorLoading" @click="activateVectorIndex">{{ t('knowledgeSpaces.ui.activateVectorIndex') }}</UButton></header><div class="p-5"><div class="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-slate-200 p-4 dark:border-slate-700"><div><p class="font-medium text-gray-900 dark:text-[#fdfcff]">{{ t('knowledgeSpaces.detail.vectorIndexStatus') }}</p><p v-if="vectorStatus?.active" class="mt-2 text-sm text-gray-600 dark:text-[#d6e2ff]">{{ t('knowledgeSpaces.ui.vectorIndexEmbedding') }}: {{ vectorStatus.active.embedding_profile_ref }} · {{ t('knowledgeSpaces.ui.vectorIndexDimensions') }}: {{ vectorStatus.active.dimensions }}</p><p v-else class="mt-2 text-sm text-warning-700 dark:text-warning-300">{{ t('knowledgeSpaces.ui.vectorIndexRequired') }}</p></div><UBadge :color="vectorStatus?.active ? 'success' : 'warning'" variant="soft">{{ vectorStatus?.active ? t('knowledgeSpaces.ui.vectorIndexActive') : t('knowledgeSpaces.ui.vectorIndexInactive') }}</UBadge></div></div></section>
      <section id="strategy" class="rounded-2xl border border-slate-200 bg-white dark:border-slate-700 dark:bg-[#0f192a]"><header class="border-b border-slate-200 p-5 dark:border-slate-700"><h2 class="font-semibold text-gray-900 dark:text-[#fdfcff]">{{ t('knowledgeSpaces.ui.strategy') }}</h2><p class="mt-1 text-sm text-gray-600 dark:text-[#d6e2ff]">{{ t('knowledgeSpaces.detail.strategyDescription') }}</p></header><dl class="grid gap-4 p-5 text-sm md:grid-cols-3"><div><dt class="text-gray-600 dark:text-[#d6e2ff]">{{ t('knowledgeSpaces.ui.ingestionProfile') }}</dt><dd class="mt-1 font-medium text-gray-900 dark:text-[#fdfcff]">{{ space.ingestion_profile_key }}</dd></div><div><dt class="text-gray-600 dark:text-[#d6e2ff]">{{ t('knowledgeSpaces.ui.indexProfileKey') }}</dt><dd class="mt-1 font-medium text-gray-900 dark:text-[#fdfcff]">{{ space.index_profile_key }}</dd></div><div><dt class="text-gray-600 dark:text-[#d6e2ff]">{{ t('knowledgeSpaces.ui.ragProfile') }}</dt><dd class="mt-1 font-medium text-gray-900 dark:text-[#fdfcff]">{{ space.rag_profile_key }}</dd></div></dl></section>
      <section id="documents" class="rounded-2xl border border-slate-200 bg-white dark:border-slate-700 dark:bg-[#0f192a]"><header class="flex flex-wrap items-center justify-between gap-3 border-b border-slate-200 p-5 dark:border-slate-700"><div><h2 class="font-semibold text-gray-900 dark:text-[#fdfcff]">{{ t('knowledgeSpaces.ui.documents') }}</h2><p class="mt-1 text-sm text-gray-600 dark:text-[#d6e2ff]">{{ t('knowledgeSpaces.detail.documentsDescription') }}</p></div><UButton icon="i-heroicons-plus" @click="documentOpen = true">{{ t('knowledgeSpaces.ui.createDocument') }}</UButton></header><div v-if="!documents.length" class="p-8 text-sm text-gray-600 dark:text-[#d6e2ff]">{{ t('knowledgeSpaces.ui.noDocuments') }}</div><div v-else class="divide-y divide-slate-100 dark:divide-slate-800"><article v-for="document in documents" :key="document.uuid" class="flex items-center justify-between gap-3 p-5"><div><p class="font-medium text-gray-900 dark:text-[#fdfcff]">{{ document.title }}</p><p class="mt-1 text-xs text-gray-600 dark:text-[#d6e2ff]">{{ t('knowledgeSpaces.ui.chunks') }}: {{ document.chunk_count }}</p></div><UButton size="xs" :loading="indexing === document.uuid" @click="indexDocument(document)">{{ t('knowledgeSpaces.ui.index') }}</UButton></article></div></section>
      <section class="rounded-2xl border border-slate-200 bg-white dark:border-slate-700 dark:bg-[#0f192a]"><header class="border-b border-slate-200 p-5 dark:border-slate-700"><h2 class="font-semibold text-gray-900 dark:text-[#fdfcff]">{{ t('knowledgeSpaces.ui.jobs') }}</h2></header><div v-if="!jobs.length" class="p-8 text-sm text-gray-600 dark:text-[#d6e2ff]">{{ t('knowledgeSpaces.ui.noJobs') }}</div><div v-else class="divide-y divide-slate-100 dark:divide-slate-800"><div v-for="job in jobs" :key="job.uuid" class="flex items-center justify-between p-4 text-sm"><span class="text-gray-900 dark:text-[#fdfcff]">{{ job.operation }}</span><UBadge :color="job.status === 'succeeded' ? 'success' : job.status === 'failed' ? 'error' : 'warning'" variant="soft">{{ job.status }}</UBadge></div></div></section>
    </template>
    <section v-else class="rounded-2xl border border-slate-200 bg-white p-12 text-center dark:border-slate-700 dark:bg-[#0f192a]"><p class="text-gray-600 dark:text-[#d6e2ff]">{{ t('knowledgeSpaces.detail.notFound') }}</p><UButton class="mt-4" :to="overviewPath">{{ t('knowledgeSpaces.detail.backToOverview') }}</UButton></section>
    <UModal v-model:open="documentOpen"><template #content><div class="p-6"><h2 class="text-lg font-semibold">{{ t('knowledgeSpaces.ui.createDocument') }}</h2><div class="mt-5 space-y-4"><UFormField :label="t('knowledgeSpaces.ui.documentTitle')" required><UInput v-model="documentDraft.title" class="w-full" /></UFormField><UFormField :label="t('knowledgeSpaces.ui.documentContent')" required><UTextarea v-model="documentDraft.content" :rows="10" class="w-full" /></UFormField><UFormField :label="t('knowledgeSpaces.ui.domainLexicon')" :help="t('knowledgeSpaces.ui.domainLexiconHelp')"><UInput v-model="documentDraft.tags" class="w-full" :placeholder="t('knowledgeSpaces.ui.domainLexiconPlaceholder')" /></UFormField></div><div class="mt-6 flex justify-end gap-3"><UButton color="neutral" variant="ghost" @click="documentOpen=false">{{ t('common.cancel') }}</UButton><UButton :loading="saving" @click="saveDocument">{{ t('common.save') }}</UButton></div></div></template></UModal>
  </main>
</template>

<script setup lang="ts">
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { useLocalKnowledgeApi, type LocalKnowledgeDocument, type LocalKnowledgeJob, type LocalKnowledgeSpace, type LocalKnowledgeVectorIndexStatus } from '~/composables/api/useLocalKnowledge'
import { useDepartmentService, type Department } from '~/composables/api/services/departmentService'
const { t } = useI18n(); const toast = useToast(); const api = useLocalKnowledgeApi(); const departmentsApi = useDepartmentService(); const route = useRoute(); const runtimeConfig = useRuntimeConfig()
const space = ref<LocalKnowledgeSpace | null>(null); const documents = ref<LocalKnowledgeDocument[]>([]); const jobs = ref<LocalKnowledgeJob[]>([]); const vectorStatus = ref<LocalKnowledgeVectorIndexStatus | null>(null); const departments = ref<Department[]>([]); const loading = ref(false); const saving = ref(false); const indexing = ref(''); const vectorLoading = ref(false); const documentOpen = ref(false); const documentDraft = reactive({ title: '', content: '', tags: '' })
const spaceUUID = computed(() => String(route.params.uuid || '')); const adminBase = computed(() => String(runtimeConfig.public?.pluginAdminBase || '/_p/com.powerx.plugins.base/admin/').replace(/\/+$/, '')); const overviewPath = computed(() => `${adminBase.value}/knowledge`)
function flatten(nodes: Department[], out: Department[] = []) { for (const item of nodes) { out.push(item); if (item.children?.length) flatten(item.children, out) }; return out }; const allDepartments = computed(() => flatten(departments.value)); function departmentName(code: string) { return allDepartments.value.find(item => item.code === code)?.name || code }
async function load() { if (!spaceUUID.value) return; loading.value = true; try { const [spaceOut, documentOut, indexOut, jobOut, tree] = await Promise.all([api.spaces(), api.documents(spaceUUID.value), api.vectorIndexStatus(spaceUUID.value), api.jobs(spaceUUID.value), departmentsApi.getDepartmentTree()]); space.value = (spaceOut.items || []).find(item => item.uuid === spaceUUID.value) || null; documents.value = documentOut.items || []; vectorStatus.value = indexOut; jobs.value = jobOut.items || []; departments.value = tree } catch { toast.add({ title: t('common.error'), description: t('knowledgeSpaces.ui.loadFailed'), color: 'error' }) } finally { loading.value = false } }
async function activateVectorIndex() { if (!space.value) return; vectorLoading.value = true; try { await api.activateVectorIndex(space.value.uuid); await load(); toast.add({ title: t('common.success'), description: t('knowledgeSpaces.ui.vectorIndexActivated'), color: 'success' }) } catch { toast.add({ title: t('common.error'), description: t('knowledgeSpaces.ui.vectorIndexActivationFailed'), color: 'error' }) } finally { vectorLoading.value = false } }
async function saveDocument() { if (!space.value || !documentDraft.title.trim() || !documentDraft.content.trim()) return; saving.value = true; try { await api.saveDocument(space.value.uuid, { title: documentDraft.title.trim(), content: documentDraft.content.trim(), tags: documentDraft.tags.split(',').map(item => item.trim()).filter(Boolean) }); documentOpen.value = false; Object.assign(documentDraft, { title: '', content: '', tags: '' }); await load(); toast.add({ title: t('common.success'), description: t('knowledgeSpaces.ui.documentSaved'), color: 'success' }) } catch { toast.add({ title: t('common.error'), description: t('knowledgeSpaces.ui.documentSaveFailed'), color: 'error' }) } finally { saving.value = false } }
async function indexDocument(document: LocalKnowledgeDocument) { indexing.value = document.uuid; try { await api.indexDocument(document.uuid); await load(); toast.add({ title: t('common.success'), description: t('knowledgeSpaces.ui.indexSucceeded'), color: 'success' }) } catch { toast.add({ title: t('common.error'), description: t('knowledgeSpaces.ui.indexFailed'), color: 'error' }) } finally { indexing.value = '' } }
watch(spaceUUID, load); onMounted(load)
</script>
