<template>
  <div class="mx-auto w-full max-w-[1600px] space-y-6 px-5 py-6 lg:px-8">
    <section class="rounded-xl border border-gray-200 bg-white p-6 dark:border-gray-800 dark:bg-slate-900">
      <UBadge color="primary" variant="soft">{{ t('knowledgeSpaces.management.badge') }}</UBadge>
      <div class="mt-3 flex flex-wrap items-start justify-between gap-4"><div><h1 class="text-2xl font-semibold">{{ t('knowledgeSpaces.management.title') }}</h1><p class="mt-2 text-sm text-gray-500">{{ t('knowledgeSpaces.management.description') }}</p></div><div class="flex gap-2"><UButton color="neutral" variant="soft" icon="i-heroicons-arrow-path" :loading="loading" @click="load">{{ t('common.refresh') }}</UButton><UButton icon="i-heroicons-plus" @click="openCreate">{{ t('knowledgeSpaces.ui.createSpace') }}</UButton></div></div>
    </section>
    <section class="rounded-xl border border-gray-200 bg-white dark:border-gray-800 dark:bg-slate-900"><div class="border-b border-gray-200 p-5 dark:border-gray-800"><h2 class="font-semibold">{{ t('knowledgeSpaces.management.localTitle') }}</h2><p class="mt-1 text-sm text-gray-500">{{ t('knowledgeSpaces.management.localDescription') }}</p></div><div v-if="!spaces.length" class="p-12 text-center text-sm text-gray-500">{{ t('knowledgeSpaces.ui.noSpaces') }}</div><div v-else class="overflow-x-auto"><table class="min-w-full text-left text-sm"><thead class="border-b border-gray-200 text-gray-500 dark:border-gray-800"><tr><th class="px-5 py-3">{{ t('knowledgeSpaces.ui.spaceName') }}</th><th class="px-5 py-3">{{ t('knowledgeSpaces.ui.department') }}</th><th class="px-5 py-3">{{ t('knowledgeSpaces.ui.ragProfile') }}</th><th class="px-5 py-3">{{ t('knowledgeSpaces.ui.documentStatus') }}</th><th class="px-5 py-3"></th></tr></thead><tbody><tr v-for="space in spaces" :key="space.uuid" class="border-b border-gray-100 dark:border-gray-800"><td class="px-5 py-4 font-medium">{{ space.name }}</td><td class="px-5 py-4">{{ departmentName(space.department_code) }}</td><td class="px-5 py-4 font-mono text-xs">{{ space.rag_profile_key }}</td><td class="px-5 py-4"><UBadge color="success" variant="subtle">{{ space.status }}</UBadge></td><td class="px-5 py-4 text-right"><UButton size="xs" color="neutral" variant="soft" @click="selectSpace(space)">{{ t('common.view') }}</UButton></td></tr></tbody></table></div></section>
    <section v-if="selected" class="rounded-xl border border-gray-200 bg-white p-5 dark:border-gray-800 dark:bg-slate-900"><div class="flex flex-wrap items-center justify-between gap-3"><div><h2 class="text-lg font-semibold">{{ selected.name }}</h2><p class="mt-1 text-sm text-gray-500">{{ departmentName(selected.department_code) }}</p></div><UButton icon="i-heroicons-plus" @click="openDocument">{{ t('knowledgeSpaces.ui.createDocument') }}</UButton></div><div class="mt-5 grid gap-3 md:grid-cols-3"><div v-for="item in profileSummary" :key="item.label" class="rounded-lg bg-gray-50 p-3 dark:bg-slate-800"><p class="text-xs text-gray-500">{{ item.label }}</p><p class="mt-1 font-mono text-sm">{{ item.value }}</p></div></div><div class="mt-7"><h3 class="font-semibold">{{ t('knowledgeSpaces.ui.documents') }}</h3><div v-if="!documents.length" class="py-8 text-center text-sm text-gray-500">{{ t('knowledgeSpaces.ui.noDocuments') }}</div><div v-else class="divide-y divide-gray-200 dark:divide-gray-800"><article v-for="document in documents" :key="document.uuid" class="flex items-center justify-between gap-3 py-4"><div><p class="font-medium">{{ document.title }}</p><p class="mt-1 text-xs text-gray-500">{{ t('knowledgeSpaces.ui.chunks') }}: {{ document.chunk_count }}</p></div><UButton size="xs" :loading="indexing === document.uuid" @click="indexDocument(document)">{{ t('knowledgeSpaces.ui.index') }}</UButton></article></div></div></section>
    <UModal v-model:open="createOpen"><template #content><div class="p-6"><h2 class="text-lg font-semibold">{{ t('knowledgeSpaces.ui.createSpace') }}</h2><p class="mt-1 text-sm text-gray-500">{{ t('knowledgeSpaces.ui.localOnly') }}</p><div class="mt-5 space-y-5"><UFormField :label="t('knowledgeSpaces.ui.spaceName')" required><UInput v-model="draft.name" class="w-full" /></UFormField><UFormField :label="t('knowledgeSpaces.ui.department')" required><USelect v-model="draft.department_code" :items="departmentOptions" class="w-full" /></UFormField><UFormField :label="t('knowledgeSpaces.ui.strategyPackage')" required><USelect v-model="draft.strategy_package_key" :items="strategyOptions" class="w-full" /></UFormField><div v-if="strategy" class="rounded-lg border p-4" :class="strategy.ready ? 'border-success-200 bg-success-50 dark:border-success-900 dark:bg-success-950/20' : 'border-warning-200 bg-warning-50 dark:border-warning-900 dark:bg-warning-950/20'"><p class="font-medium">{{ t('knowledgeSpaces.ui.strategyAutoMapping') }}</p><dl class="mt-3 grid gap-3 text-sm md:grid-cols-3"><div><dt class="text-gray-500">{{ t('knowledgeSpaces.ui.ingestionProfile') }}</dt><dd class="font-mono">{{ strategy.profile_key }}</dd></div><div><dt class="text-gray-500">{{ t('knowledgeSpaces.ui.indexProfileKey') }}</dt><dd class="font-mono">{{ strategy.profile_key }}</dd></div><div><dt class="text-gray-500">{{ t('knowledgeSpaces.ui.ragProfile') }}</dt><dd class="font-mono">{{ strategy.profile_key }}</dd></div></dl><p class="mt-3 text-sm">{{ strategy.ready ? t('knowledgeSpaces.ui.strategyReady') : t('knowledgeSpaces.ui.strategyUnavailable', { requirements: strategy.missing_requirements.join(', ') }) }}</p></div></div><div class="mt-6 flex justify-end gap-3"><UButton color="neutral" variant="ghost" @click="createOpen=false">{{ t('common.cancel') }}</UButton><UButton :disabled="!canSave" :loading="saving" @click="saveSpace">{{ t('knowledgeSpaces.ui.createSpace') }}</UButton></div></div></template></UModal>
    <UModal v-model:open="documentOpen"><template #content><div class="p-6"><h2 class="text-lg font-semibold">{{ t('knowledgeSpaces.ui.createDocument') }}</h2><div class="mt-5 space-y-4"><UFormField :label="t('knowledgeSpaces.ui.documentTitle')" required><UInput v-model="documentDraft.title" class="w-full" /></UFormField><UFormField :label="t('knowledgeSpaces.ui.documentContent')" required><UTextarea v-model="documentDraft.content" :rows="12" class="w-full" /></UFormField></div><div class="mt-6 flex justify-end gap-3"><UButton color="neutral" variant="ghost" @click="documentOpen=false">{{ t('common.cancel') }}</UButton><UButton :loading="saving" @click="saveDocument">{{ t('common.save') }}</UButton></div></div></template></UModal>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { useLocalKnowledgeApi, type KnowledgeStrategyPackage, type LocalKnowledgeDocument, type LocalKnowledgeSpace } from '~/composables/api/useLocalKnowledge'
import { useDepartmentService, type Department } from '~/composables/api/services/departmentService'
const { t } = useI18n(); const toast = useToast(); const api = useLocalKnowledgeApi(); const departmentsApi = useDepartmentService()
const spaces = ref<LocalKnowledgeSpace[]>([]); const departments = ref<Department[]>([]); const strategies = ref<KnowledgeStrategyPackage[]>([]); const selected = ref<LocalKnowledgeSpace | null>(null); const documents = ref<LocalKnowledgeDocument[]>([]); const loading = ref(false); const saving = ref(false); const indexing = ref(''); const createOpen = ref(false); const documentOpen = ref(false)
const draft = reactive({ name: '', department_code: '', strategy_package_key: '' }); const documentDraft = reactive({ title: '', content: '' })
function flatten(nodes: Department[], output: Department[] = []) { for (const node of nodes) { output.push(node); if (node.children?.length) flatten(node.children, output) }; return output }
const allDepartments = computed(() => flatten(departments.value)); const departmentOptions = computed(() => allDepartments.value.map(item => ({ label: item.name, value: item.code }))); const strategy = computed(() => strategies.value.find(item => item.key === draft.strategy_package_key)); const strategyOptions = computed(() => strategies.value.map(item => ({ label: item.key, value: item.key, disabled: !item.ready }))); const canSave = computed(() => !!draft.name.trim() && !!draft.department_code && !!strategy.value?.ready); const profileSummary = computed(() => selected.value ? [{ label: t('knowledgeSpaces.ui.ingestionProfile'), value: selected.value.ingestion_profile_key }, { label: t('knowledgeSpaces.ui.indexProfileKey'), value: selected.value.index_profile_key }, { label: t('knowledgeSpaces.ui.ragProfile'), value: selected.value.rag_profile_key }] : [])
function departmentName(code: string) { return allDepartments.value.find(item => item.code === code)?.name || code }
async function load() { loading.value = true; try { const [spaceOut, strategyOut, departmentTree] = await Promise.all([api.spaces(), api.strategyPackages(), departmentsApi.getDepartmentTree()]); spaces.value = spaceOut.items || []; strategies.value = strategyOut.items || []; departments.value = departmentTree; if (selected.value) { const next = spaces.value.find(item => item.uuid === selected.value?.uuid); if (next) await selectSpace(next) } } catch { toast.add({ title: t('common.error'), description: t('knowledgeSpaces.ui.loadFailed'), color: 'error' }) } finally { loading.value = false } }
function openCreate() { Object.assign(draft, { name: '', department_code: departmentOptions.value[0]?.value || '', strategy_package_key: strategies.value.find(item => item.ready)?.key || '' }); createOpen.value = true }
async function saveSpace() { if (!canSave.value) return; saving.value = true; try { const saved = await api.saveSpace({ ...draft, name: draft.name.trim() }); createOpen.value = false; await load(); await selectSpace(saved); toast.add({ title: t('common.success'), description: t('knowledgeSpaces.ui.spaceSaved'), color: 'success' }) } catch { toast.add({ title: t('common.error'), description: t('knowledgeSpaces.ui.spaceSaveFailed'), color: 'error' }) } finally { saving.value = false } }
async function selectSpace(space: LocalKnowledgeSpace) { selected.value = space; const out = await api.documents(space.uuid); documents.value = out.items || [] }
function openDocument() { Object.assign(documentDraft, { title: '', content: '' }); documentOpen.value = true }
async function saveDocument() { if (!selected.value || !documentDraft.title.trim() || !documentDraft.content.trim()) return; saving.value = true; try { await api.saveDocument(selected.value.uuid, documentDraft); documentOpen.value = false; await selectSpace(selected.value); toast.add({ title: t('common.success'), description: t('knowledgeSpaces.ui.documentSaved'), color: 'success' }) } catch { toast.add({ title: t('common.error'), description: t('knowledgeSpaces.ui.documentSaveFailed'), color: 'error' }) } finally { saving.value = false } }
async function indexDocument(document: LocalKnowledgeDocument) { indexing.value = document.uuid; try { await api.indexDocument(document.uuid); await selectSpace(selected.value!); toast.add({ title: t('common.success'), description: t('knowledgeSpaces.ui.indexSucceeded'), color: 'success' }) } catch { toast.add({ title: t('common.error'), description: t('knowledgeSpaces.ui.indexFailed'), color: 'error' }) } finally { indexing.value = '' } }
onMounted(load)
</script>
