using System.Net;
using System.Net.Http.Headers;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using Microsoft.Extensions.DependencyInjection;
using PowerXPlugin.Framework.Runtime.Common;

namespace PowerXPlugin.Framework.Runtime.PluginRuntime;
public sealed record PluginRuntimeScope(string TenantUuid);
public sealed record PluginKnowledgeSpace([property:JsonPropertyName("uuid")]string Uuid,[property:JsonPropertyName("space_name")]string SpaceName,string Status,[property:JsonPropertyName("department_code")]string DepartmentCode,[property:JsonPropertyName("rag_profile_key")]string RagProfileKey);
public sealed record PluginPage<T>(IReadOnlyList<T> Items,long Total,int Page,int PageSize);
public sealed record ListPluginKnowledgeSpacesRequest(int Page=1,int PageSize=50,string Status="",string Keyword="");
public sealed record PluginAgent([property:JsonPropertyName("uuid")]string Uuid,string Key,string Name,string Status,[property:JsonPropertyName("skill_ids")]IReadOnlyList<string>? SkillIds=null);
public sealed record InstantiatePluginAgentRequest(string Name,string Environment="",string Key="",IReadOnlyList<string>? SkillIds=null,IReadOnlyList<string>? KnowledgeBaseIds=null,IReadOnlyDictionary<string,JsonElement>? Parameters=null);
public interface IPluginRuntimeService { Task<PluginPage<PluginKnowledgeSpace>> ListKnowledgeSpacesAsync(PluginRuntimeScope scope,ListPluginKnowledgeSpacesRequest request,CancellationToken ct=default); Task<PluginAgent> InstantiateAgentAsync(PluginRuntimeScope scope,InstantiatePluginAgentRequest request,CancellationToken ct=default); Task<IReadOnlyList<PluginAgent>> ListAgentsAsync(PluginRuntimeScope scope,string environment="",string status="",CancellationToken ct=default); }
public interface ILocalPluginRuntimeService: IPluginRuntimeService {}
public sealed class LocalPluginRuntimeAdapter(ILocalPluginRuntimeService store):IPluginRuntimeService { private readonly ILocalPluginRuntimeService _store=store??throw new ArgumentNullException(nameof(store)); private static void V(PluginRuntimeScope s){if(!Guid.TryParse(s.TenantUuid,out var x)||x==Guid.Empty||x.ToString()!=s.TenantUuid)throw new PluginRuntimeException(PluginRuntimeErrors.InvalidArgument);} public Task<PluginPage<PluginKnowledgeSpace>> ListKnowledgeSpacesAsync(PluginRuntimeScope s,ListPluginKnowledgeSpacesRequest r,CancellationToken ct=default){V(s);return _store.ListKnowledgeSpacesAsync(s,r,ct);} public Task<PluginAgent> InstantiateAgentAsync(PluginRuntimeScope s,InstantiatePluginAgentRequest r,CancellationToken ct=default){V(s);if(string.IsNullOrWhiteSpace(r.Name))throw new PluginRuntimeException(PluginRuntimeErrors.InvalidArgument);return _store.InstantiateAgentAsync(s,r,ct);} public Task<IReadOnlyList<PluginAgent>> ListAgentsAsync(PluginRuntimeScope s,string e="",string st="",CancellationToken ct=default){V(s);return _store.ListAgentsAsync(s,e,st,ct);} }
public sealed class PowerXPluginRuntimeClient(string baseUrl,string tenantUuid,IServiceCredentialProvider credentials,HttpClient? http=null):IPluginRuntimeService { private readonly string _base=baseUrl.TrimEnd('/');private readonly string _tenant=tenantUuid;private readonly IServiceCredentialProvider _credentials=credentials;private readonly HttpClient _http=http??new();private void V(PluginRuntimeScope s){if(s.TenantUuid!=_tenant)throw new PluginRuntimeException(PluginRuntimeErrors.TenantMismatch);} public Task<PluginPage<PluginKnowledgeSpace>> ListKnowledgeSpacesAsync(PluginRuntimeScope s,ListPluginKnowledgeSpacesRequest r,CancellationToken ct=default)=>Send<PluginPage<PluginKnowledgeSpace>>(s,HttpMethod.Get,"/api/v1/tenant/plugin-runtime/knowledge-spaces?page="+Math.Max(1,r.Page)+"&page_size="+Math.Clamp(r.PageSize,1,100),null,ct); public Task<PluginAgent> InstantiateAgentAsync(PluginRuntimeScope s,InstantiatePluginAgentRequest r,CancellationToken ct=default)=>Send<PluginAgent>(s,HttpMethod.Post,"/api/v1/tenant/plugin-runtime/agents/instantiate",new{env=r.Environment,key=r.Key,name=r.Name,skill_ids=r.SkillIds??[],knowledge_base_ids=r.KnowledgeBaseIds??[],parameters=r.Parameters},ct); public Task<IReadOnlyList<PluginAgent>> ListAgentsAsync(PluginRuntimeScope s,string e="",string st="",CancellationToken ct=default)=>Send<IReadOnlyList<PluginAgent>>(s,HttpMethod.Get,"/api/v1/tenant/plugin-runtime/agents",null,ct); private async Task<T> Send<T>(PluginRuntimeScope s,HttpMethod m,string path,object? body,CancellationToken ct){V(s);var c=(await _credentials.GetCredentialAsync(ct)).Validate();using var q=new HttpRequestMessage(m,_base+path);q.Headers.Authorization=new AuthenticationHeaderValue(c.NormalizedAuthScheme,c.Value);if(body is not null)q.Content=new StringContent(JsonSerializer.Serialize(body),Encoding.UTF8,"application/json");using var r=await _http.SendAsync(q,ct);var raw=await r.Content.ReadAsStringAsync(ct);if(!r.IsSuccessStatusCode)throw new PluginRuntimeException(r.StatusCode==HttpStatusCode.Forbidden?PluginRuntimeErrors.Forbidden:PluginRuntimeErrors.Upstream);using var j=JsonDocument.Parse(raw);if(!j.RootElement.TryGetProperty("data",out var d))throw new PluginRuntimeException(PluginRuntimeErrors.InvalidResponse);return JsonSerializer.Deserialize<T>(d.GetRawText(),new JsonSerializerOptions(JsonSerializerDefaults.Web))??throw new PluginRuntimeException(PluginRuntimeErrors.InvalidResponse);} }
public static class PluginRuntimeExtensions { public static IServiceCollection AddPowerXPluginRuntime(this IServiceCollection s,ProviderMode m,Func<IServiceProvider,IPluginRuntimeService> l,Func<IServiceProvider,IPluginRuntimeService> d)=>s.AddPowerXRuntime("plugin-runtime",m,l,d); }
public static class PluginRuntimeErrors { public const string InvalidArgument="FRAMEWORK_PLUGIN_RUNTIME_INVALID_ARGUMENT",InvalidResponse="FRAMEWORK_PLUGIN_RUNTIME_INVALID_RESPONSE",TenantMismatch="FRAMEWORK_PLUGIN_RUNTIME_TENANT_MISMATCH",Forbidden="FRAMEWORK_PLUGIN_RUNTIME_FORBIDDEN",Upstream="FRAMEWORK_PLUGIN_RUNTIME_UPSTREAM_DEPENDENCY";} public sealed class PluginRuntimeException(string code):InvalidOperationException(code){public string Code{get;}=code;}
