// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: gateway.proto

package gatewaypb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IntegrationGatewayTenantService_InvokeCapability_FullMethodName = "/plugin.framework.integration.gateway.v1.IntegrationGatewayTenantService/InvokeCapability"
)

// IntegrationGatewayTenantServiceClient is the client API for IntegrationGatewayTenantService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IntegrationGatewayTenantServiceClient interface {
	InvokeCapability(ctx context.Context, in *InvokeCapabilityRequest, opts ...grpc.CallOption) (*InvokeCapabilityResponse, error)
}

type integrationGatewayTenantServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIntegrationGatewayTenantServiceClient(cc grpc.ClientConnInterface) IntegrationGatewayTenantServiceClient {
	return &integrationGatewayTenantServiceClient{cc}
}

func (c *integrationGatewayTenantServiceClient) InvokeCapability(ctx context.Context, in *InvokeCapabilityRequest, opts ...grpc.CallOption) (*InvokeCapabilityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InvokeCapabilityResponse)
	err := c.cc.Invoke(ctx, IntegrationGatewayTenantService_InvokeCapability_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IntegrationGatewayTenantServiceServer is the server API for IntegrationGatewayTenantService service.
// All implementations must embed UnimplementedIntegrationGatewayTenantServiceServer
// for forward compatibility.
type IntegrationGatewayTenantServiceServer interface {
	InvokeCapability(context.Context, *InvokeCapabilityRequest) (*InvokeCapabilityResponse, error)
	mustEmbedUnimplementedIntegrationGatewayTenantServiceServer()
}

// UnimplementedIntegrationGatewayTenantServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIntegrationGatewayTenantServiceServer struct{}

func (UnimplementedIntegrationGatewayTenantServiceServer) InvokeCapability(context.Context, *InvokeCapabilityRequest) (*InvokeCapabilityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InvokeCapability not implemented")
}
func (UnimplementedIntegrationGatewayTenantServiceServer) mustEmbedUnimplementedIntegrationGatewayTenantServiceServer() {
}
func (UnimplementedIntegrationGatewayTenantServiceServer) testEmbeddedByValue() {}

// UnsafeIntegrationGatewayTenantServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IntegrationGatewayTenantServiceServer will
// result in compilation errors.
type UnsafeIntegrationGatewayTenantServiceServer interface {
	mustEmbedUnimplementedIntegrationGatewayTenantServiceServer()
}

func RegisterIntegrationGatewayTenantServiceServer(s grpc.ServiceRegistrar, srv IntegrationGatewayTenantServiceServer) {
	// If the following call pancis, it indicates UnimplementedIntegrationGatewayTenantServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IntegrationGatewayTenantService_ServiceDesc, srv)
}

func _IntegrationGatewayTenantService_InvokeCapability_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvokeCapabilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegrationGatewayTenantServiceServer).InvokeCapability(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IntegrationGatewayTenantService_InvokeCapability_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegrationGatewayTenantServiceServer).InvokeCapability(ctx, req.(*InvokeCapabilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IntegrationGatewayTenantService_ServiceDesc is the grpc.ServiceDesc for IntegrationGatewayTenantService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IntegrationGatewayTenantService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "plugin.framework.integration.gateway.v1.IntegrationGatewayTenantService",
	HandlerType: (*IntegrationGatewayTenantServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InvokeCapability",
			Handler:    _IntegrationGatewayTenantService_InvokeCapability_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gateway.proto",
}
